import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import './globals.css';
import Navbar from '@/components/_navbar/index';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sacling Ethereum 2024',
  description: 'Generated by create next app',
};

// Updated RootLayout to handle session being undefined
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <Navbar />
            <Providers>{children}</Providers>
      </body>
    </html>
  );
}
